const FILTER = 'FILTER';

const INPUT = 'INPUT';

const ADD = 'ADD';

const UPDATE = 'UPDATE';

const DELETE = 'DELETE';

const COMPLETE = 'COMPLETE';

const START_FETCH_TODOS = 'START_FETCH_TODOS';

const FINISH_FETCH_TODOS = 'FINISH_FETCH_TODOS';

const ERROR_FETCH_TODOS = 'ERROR_FETCH_TODOS';

const INVALIDATE_TODOS = 'INVALIDATE_TODOS';

const START_UPDATE_TODO = 'START_UPDATE_TODO';

const FINISH_UPDATE_TODO = 'FINISH_UPDATE_TODO';

const ERROR_UPDATE_TODO = 'ERROR_UPDATE_TODO';

export {
    FILTER, INPUT, ADD, COMPLETE, INVALIDATE_TODOS, START_FETCH_TODOS,
    FINISH_FETCH_TODOS, ERROR_FETCH_TODOS, START_UPDATE_TODO, FINISH_UPDATE_TODO,
    ERROR_UPDATE_TODO, UPDATE, DELETE
};
