const FILTER = 'FILTER';

const INPUT = 'INPUT';

const ADD = 'ADD';

const COMPLETE = 'COMPLETE';

const START_FETCH_TODOS = 'START_FETCH_TODOS';

const FINISH_FETCH_TODOS = 'FINISH_FETCH_TODOS';

export {FILTER, INPUT, ADD, COMPLETE, START_FETCH_TODOS, FINISH_FETCH_TODOS};
